### ISSUE TITLE
[Bug]: System.MissingMethodException WasmScheduler

### ISSUE THREAD

**Issue by OmidID** [reactiveui/Reactive.Wasm#36]
### Describe the bug 🐞

Hello,

I trying to migrate my project to blazor wasm and we face an issue. For me it is complicated to say where is the error exactly. But what I am sure there is a bug while Rx library try to find a method from dotnet library

https://github.com/reactiveui/Reactive.Wasm/blob/main/src/System.Reactive.Wasm/Internal/WasmScheduler.cs#L135

Any quick solution to solve the problem on our side until the fix done on Rx library?

Thanks,

### Step to reproduce

```csharp
this.WhenAnyValue(x => x.Filter)
            .Throttle(TimeSpan.FromMilliseconds(SearchTimeout))
            .ObserveOn(RxApp.MainThreadScheduler)
            .Subscribe(DoFilter);
```

### Reproduction repository

https://github.com/reactiveui/ReactiveUI

### Expected behavior

A simple code that call WasmScheduler

### Screenshots 🖼️

![image](https://github.com/user-attachments/assets/8d9be93d-48ca-402f-8e31-2f6eea170201)

```
[MONO]  w\1/s/src/mono/mono/metadata/icall.c:6177  <disabled>
[MONO]  w\1/s/src/mono/mono/metadata/icall.c:6168  <disabled>
(null)
Unhandled Exception:
System.MissingMethodException: assembly:<unknown assembly> type:<unknown type> member:(null)
   at System.Reactive.Concurrency.WasmScheduler.WasmRuntime.ScheduleTimeout(Int32 timeout, Action action)
       in d:\a\1\s\src\System.Reactive.Wasm\Internal\WasmScheduler.cs:line 145
   at System.Reactive.Concurrency.WasmScheduler.Schedule[ObserveOnObserverNew`1]
       (ObserveOnObserverNew`1 state, Func`3 action)
       in d:\a\1\s\src\System.Reactive.Wasm\Internal\WasmScheduler.cs:line 34
   at System.Reactive.ObserveOnObserverNew`1[[System.String, System.Private.CoreLib, Version=8.0.0.0,
       Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Schedule()
   at System.Reactive.Linq.ObservableImpl.Throttle`1[[System.String, System.Private.CoreLib, Version=8.0.0.0,
       Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].OnNext(String value)
   at System.Reactive.Sink`1[[System.String, System.Private.CoreLib, Version=8.0.0.0,
       Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ForwardOnNext(String value)
   at System.Reactive.Linq.ObservableImpl.Throttle`1.⟦?⟧ OnNext⟦?⟧(⟦?⟧ value)
   at System.Reactive.Concurrency.Scheduler.Invoke[ValueTuple`2](ValueTuple`2 tuple)
   at System.Reactive.Concurrency.Scheduler.⟦?⟧(ValueTuple`2[System.String, System.Private.CoreLib,
       Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e], System.Private.CoreLib,
       Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e].⟦?⟧(ValueTuple`2 tuple)
```

Note looks to be a out of date sync with possibly System.Reactive

**Comment by glennawatson** [comment]
Update to https://github.com/reactiveui/Reactive.Wasm/releases/tag/3.0.1 should solve your issue.

Uno release coming soon if that is the platform you are using.

**Comment by OmidID** [comment]
Hello. Thanks @glennawatson 
It is Blazor. I am not sure if still client need that feature as it was very long time ago we use a button instead of Throttle.

**Comment by glennawatson** [comment]
> Hello. Thanks @glennawatson 
> It is Blazor. I am not sure if still client need that feature as it was very long time ago we use a button instead of Throttle.

No problem. Our fault for not getting on it quicker. Thanks for the report n

**Comment by OmidID** [comment]
Ah. No problem, thank you so much anyway 🙏
